### ISSUE TITLE
Support multiple recipients

### ISSUE THREAD

**Issue by sihoang** [WeTrustPlatform/charity-challenge-contracts#9]
If the challenge succeeds, fund will be sent to multiple recipients by a defined ratio.

**Comment by sihoang** [comment]
This will not be in the soft launch.  It's for the Vitalik challenge which is still pending business team's confirmation.

**Comment by sihoang** [comment]
since Vitalik suit challenge is ready, we would need this merged for the release https://cloudflare-ipfs.com/ipfs/QmRX5eYxoUMMP6HyyvaEng3NtLMFVPJ3KoepUReaQHMkpd/?ethereum_node_http=https%3a%2f%2feth-mainnet.alchemyapi.io%2fjsonrpc%2f7sE1TzCIRIQA3NJPD5wg7YRiVjhxuWAE&augur_node=wss%3a%2f%2faugur-node.augur.casino#!/market?id=0xcaa44b7fa605827906c5a12c003f4143bedf65d6

**Comment by kivutar** [comment]
This will have consequences on the UI.
We are using getters for the recipient, to display the npo address in the UI.
